"""Locate window and CLIP confidence thresholds."""

from __future__ import annotations

LOCATE_CROP_ANCHOR_WINDOW_SEC = 5.0
LOCATE_CLIP_WINDOW_TIGHT_SEC = 10.0
LOCATE_CLIP_WINDOW_WIDE_SEC = 40.0
LOCATE_CLIP_WINDOW_UNSTABLE_MARGIN = 0.05
LOCATE_CLIP_CONFIDENCE_LOW = 0.42
LOCATE_CLIP_CONFIDENCE_HIGH = 0.99
LOCATE_CROP_MIN_CLIP_SCORE = 0.6
LOCATE_CROP_ANCHOR_MIN_GAIN = 0.03
CLIP_CONFIDENCE_VERY_HIGH = 0.85
CLIP_CONFIDENCE_HIGH = 0.70
CLIP_CONFIDENCE_MEDIUM = 0.60
