"""Manage embedded nginx for team video sharing."""

from __future__ import annotations

import os
import subprocess
import time
from typing import Dict, List, Optional

from src.app.logging_utils import get_logger
from src.services.team_media_map import build_media_mounts
from src.services.team_paths import (
    get_nginx_conf_d_dir,
    get_nginx_exe,
    get_nginx_root,
    get_nginx_videos_conf_path,
    nginx_bundle_ready,
)

logger = get_logger("team_nginx")

_process: Optional[subprocess.Popen] = None


def ensure_nginx_runtime_dirs() -> None:
    """Fresh clones omit gitignored logs/temp; nginx needs them before any -t/-s/start."""
    root = get_nginx_root()
    os.makedirs(os.path.join(root, "logs"), exist_ok=True)
    os.makedirs(os.path.join(root, "temp"), exist_ok=True)
    os.makedirs(get_nginx_conf_d_dir(), exist_ok=True)


def _nginx_prefix_root() -> str:
    """nginx ``-p`` prefix with trailing separator (Windows long path)."""
    root = get_nginx_root()
    if not root.endswith(("\\", "/")):
        root = root + os.sep
    return root


def _run_nginx(args: List[str], *, timeout: float = 8.0) -> subprocess.CompletedProcess:
    ensure_nginx_runtime_dirs()
    exe = get_nginx_exe()
    root = get_nginx_root()
    prefix = _nginx_prefix_root()
    # Relative -c under -p: absolute 8.3 conf paths break Win nginx CreateFile.
    conf = "conf/nginx.conf"
    cmd = [exe, "-p", prefix, "-c", conf, *args]
    logger.info("nginx cmd: %s", " ".join(cmd))
    return subprocess.run(
        cmd,
        cwd=root,
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )


def _nginx_quoted_path(path: str) -> str:
    """Quote a filesystem path for nginx directives (spaces / unicode safe)."""
    text = str(path or "").replace("\\", "/")
    text = text.replace('"', '\\"')
    return f'"{text}"'


def write_videos_conf(*, library_paths: List[str], listen_port: int) -> List[Dict[str, str]]:
    mounts = build_media_mounts(library_paths)
    os.makedirs(get_nginx_conf_d_dir(), exist_ok=True)
    lines = [
        "# Generated by VideoSeek team mode — do not edit by hand while the app is running.",
        "server {",
        f"    listen       {int(listen_port)};",
        "    server_name  localhost;",
        "    charset      utf-8;",
        "",
        "    location = /health {",
        "        default_type text/plain;",
        '        return 200 "ok\\n";',
        "    }",
        "",
    ]
    if not mounts:
        lines.extend(
            [
                "    location /videos/ {",
                "        default_type text/plain;",
                '        return 503 "no libraries mounted\\n";',
                "    }",
            ]
        )
    else:
        for mount in mounts:
            alias = _nginx_quoted_path(mount["alias"])
            prefix = mount["url_prefix"].rstrip("/") + "/"
            # Keep comments ASCII-safe-ish: avoid breaking conf parsers on odd chars
            comment = str(mount["library_path"]).replace("\\", "/")
            lines.extend(
                [
                    f"    # {comment}",
                    f"    location {prefix} {{",
                    f"        alias   {alias};",
                    "        autoindex on;",
                    "        add_header Accept-Ranges bytes;",
                    "    }",
                    "",
                ]
            )
    lines.append("}")
    lines.append("")
    path = get_nginx_videos_conf_path()
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    logger.info("Wrote nginx videos conf: %s (%d mounts)", path, len(mounts))
    return mounts


def test_config() -> tuple[bool, str]:
    if not nginx_bundle_ready():
        return False, "nginx bundle missing under server/nginx"
    try:
        completed = _run_nginx(["-t"])
    except (OSError, subprocess.TimeoutExpired) as exc:
        return False, str(exc)
    detail = (completed.stderr or completed.stdout or "").strip()
    return completed.returncode == 0, detail


def start_nginx(*, library_paths: List[str], listen_port: int) -> List[Dict[str, str]]:
    global _process
    if not nginx_bundle_ready():
        raise RuntimeError("Embedded nginx not found. Expected server/nginx/nginx.exe")
    ensure_nginx_runtime_dirs()
    mounts = write_videos_conf(library_paths=library_paths, listen_port=listen_port)
    ok, detail = test_config()
    if not ok:
        raise RuntimeError(f"nginx config test failed: {detail or 'unknown error'}")

    # Prefer controlling via master process signals; start if not running.
    if is_nginx_running():
        try:
            reload_nginx()
            return mounts
        except RuntimeError as exc:
            # Windows: stale pid / wrong process → OpenEvent("Global\\ngx_reload_*") fails.
            logger.warning("nginx reload failed (%s); forcing restart", exc)
            stop_nginx()

    exe = get_nginx_exe()
    root = get_nginx_root()
    prefix = _nginx_prefix_root()
    conf = "conf/nginx.conf"
    creationflags = 0
    if os.name == "nt":
        # CREATE_NO_WINDOW only — DETACHED_PROCESS can prevent a reliable master process.
        creationflags = getattr(subprocess, "CREATE_NO_WINDOW", 0)
    _process = subprocess.Popen(
        [exe, "-p", prefix, "-c", conf],
        cwd=root,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        creationflags=creationflags,
    )
    time.sleep(0.35)
    if not is_nginx_running():
        # Fallback: maybe already started outside our process handle
        ping = _run_nginx(["-t"])
        if ping.returncode != 0:
            raise RuntimeError("nginx failed to start")
    logger.info("nginx started on port %s", listen_port)
    return mounts


def reload_nginx() -> None:
    completed = _run_nginx(["-s", "reload"])
    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout or "").strip()
        raise RuntimeError(detail or "nginx reload failed")


def stop_nginx() -> None:
    global _process
    if not nginx_bundle_ready():
        return
    try:
        completed = _run_nginx(["-s", "stop"])
        if completed.returncode != 0:
            logger.warning("nginx stop: %s", (completed.stderr or completed.stdout or "").strip())
    except (OSError, subprocess.TimeoutExpired) as exc:
        logger.warning("nginx stop failed: %s", exc)
    # Windows: master may linger briefly; force-kill by pid file if still alive.
    if is_nginx_running():
        _force_kill_nginx_pid()
        time.sleep(0.2)
    if _process is not None:
        try:
            if _process.poll() is None:
                _process.terminate()
        except Exception:
            pass
    _process = None


def _force_kill_nginx_pid() -> None:
    root = get_nginx_root()
    pid_file = os.path.join(root, "logs", "nginx.pid")
    if not os.path.isfile(pid_file):
        return
    try:
        pid = int(open(pid_file, encoding="utf-8").read().strip())
    except (OSError, ValueError):
        return
    if pid <= 0:
        return
    if os.name == "nt":
        try:
            subprocess.run(
                ["taskkill", "/F", "/PID", str(pid), "/T"],
                capture_output=True,
                text=True,
                timeout=5,
                check=False,
                creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0),
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            logger.warning("taskkill nginx failed: %s", exc)
    else:
        try:
            os.kill(pid, 15)
        except OSError:
            pass


def _windows_pid_is_nginx(pid: int) -> bool:
    """True only if *pid* is a live nginx.exe (avoids stale pid reuse)."""
    try:
        import ctypes
        from ctypes import wintypes

        kernel32 = ctypes.windll.kernel32  # type: ignore[attr-defined]
        PROCESS_QUERY_LIMITED_INFORMATION = 0x1000
        handle = kernel32.OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, False, int(pid))
        if not handle:
            return False
        try:
            QueryFullProcessImageNameW = kernel32.QueryFullProcessImageNameW
            QueryFullProcessImageNameW.argtypes = [
                wintypes.HANDLE,
                wintypes.DWORD,
                wintypes.LPWSTR,
                ctypes.POINTER(wintypes.DWORD),
            ]
            QueryFullProcessImageNameW.restype = wintypes.BOOL
            size = wintypes.DWORD(32768)
            buf = ctypes.create_unicode_buffer(size.value)
            if not QueryFullProcessImageNameW(handle, 0, buf, ctypes.byref(size)):
                return False
            image = (buf.value or "").replace("/", "\\").lower()
            return image.endswith("\\nginx.exe") or os.path.basename(image) == "nginx.exe"
        finally:
            kernel32.CloseHandle(handle)
    except Exception:
        return False


def is_nginx_running() -> bool:
    root = get_nginx_root()
    pid_file = os.path.join(root, "logs", "nginx.pid")
    if not os.path.isfile(pid_file):
        return False
    try:
        raw = open(pid_file, encoding="utf-8").read().strip()
        pid = int(raw)
    except (OSError, ValueError):
        return False
    if pid <= 0:
        return False
    if os.name == "nt":
        return _windows_pid_is_nginx(pid)
    try:
        os.kill(pid, 0)
        return True
    except OSError:
        return False
