COPY_OVERRIDES = {
    "zh": {
        "app_subtitle": "本地视频语义检索与片段预览",
        "hero_title": "搜索、视频下载、参数设置分区操作",
        "hero_body": "按页面分工操作，减少干扰，定位更快。",
        "search_page_desc": "在独立工作区完成查询、预览与结果分析。",
        "link_page_title": "视频下载",
        "link_page_desc": "粘贴视频链接，检测后在列表中逐条或批量下载；每行可单独选画质，默认最高可用。",
        "library_page_desc": "管理本地视频目录、索引状态与向量数据。",
        "settings_page_desc": "统一管理抽帧、检索、预览与运行参数。",
        "clear": "清空输入",
        "setting_fps": "抽帧频率",
        "setting_fps_hint": "本地索引与网络构建共用。值越高覆盖越细，但耗时与占用更高。",
        "setting_remote_max_frames": "网库限帧",
        "setting_remote_max_frames_hint": "安全上限。仅在视频很长且 FPS 较高时触发，通常保持默认。",
        "setting_top_k_hint": "每次检索最多返回的结果条数。",
        "setting_search_mode_hint": "按帧检索更细，按片段检索更语义化。",
        "settings_hint": "修改后点击“保存设置”生效。",
        "saved_settings": "设置已保存。",
        "settings_saved_no_rebuild": "设置已保存，后续检索将使用新参数。",
        "settings_saved_chunk_rebuild": "设置已保存。片段相关参数已变更，需重建索引后生效。",
        "settings_saved_full_rebuild": "设置已保存。FPS 已变更，需重建索引（含重新抽帧与向量生成）。",
        "settings_saved_mixed_rebuild": "设置已保存。FPS 与片段参数已变更，需完整重建索引。",
        "library_vectors_title": "本地向量文件详情",
        "details_title_default": "详情",
        "details_copy_json": "复制 JSON",
        "details_export_json": "导出 JSON",
        "details_empty": "暂无可显示数据。",
        "ready": "就绪",
        "searching": "正在检索...",
        "search_done": "检索完成：耗时 {duration:.2f}s，结果 {count} 条。",
        "no_results": "未找到匹配结果。",
        "search_failed": "检索失败。",
        "empty_query": "请先输入文本或上传图片。",
        "query_too_short": "输入太短，建议至少描述主体或动作，例如：“夜晚街道上奔跑的男人”。",
        "query_generic_title": "搜索提示",
        "query_generic_hint": "当前描述比较泛，建议补充主体、动作、场景或镜头特征。",
        "query_refined": "已自动整理输入：{query}",
        "warning_title": "提示",
        "error_title": "操作失败",
        "success_title": "操作完成",
        "generic_detail": "详细信息：{detail}",
    },
    "en": {
        "app_subtitle": "Semantic video retrieval with fast clip preview",
        "hero_title": "Operate Search, Video Download, and Settings independently",
        "hero_body": "Clear page boundaries reduce context switching and mistakes.",
        "search_page_desc": "Run query, preview, and result review in a dedicated workspace.",
        "link_page_title": "Video Download",
        "link_page_desc": "Paste video URLs, probe them, then download one row or all. Each row has its own quality; default is highest available.",
        "library_page_desc": "Manage local folders, index status, and vector assets.",
        "settings_page_desc": "Configure sampling, retrieval, preview, and runtime behavior.",
        "clear": "Clear Input",
        "setting_fps": "Sample FPS",
        "setting_fps_hint": "This is the base sampling density. The app automatically samples short videos more densely and long videos more sparsely.",
        "setting_sampling_fps_mode": "Sampling Mode",
        "setting_sampling_fps_mode_hint": "Fixed mode always uses the unified FPS. Dynamic mode matches the FPS rule for the current video duration.",
        "setting_sampling_fps_mode_fixed": "Fixed",
        "setting_sampling_fps_mode_dynamic": "Dynamic",
        "setting_sampling_fps_rules_placeholder": "Example: 0-10m=2; 10m-=1",
        "setting_sampling_fps_rules_edit": "Edit Rules",
        "setting_sampling_fps_rules_hint": "Use 'start-end=FPS' rules with minute units only (m), for example 10m or 60m. Leave the end empty for no upper bound.",
        "setting_sampling_fps_rules_invalid": "Invalid dynamic sampling rules. Use 'start-end=FPS', for example: 0-10m=2; 10m-=1",
        "sampling_rules_title": "Edit Sampling Rules",
        "sampling_rules_hint": "Fill one duration range and FPS per row. Minute units only (m), such as 10m or 60m. Leave the end empty for no upper bound.",
        "sampling_rules_col_start": "Start",
        "sampling_rules_col_end": "End",
        "sampling_rules_col_fps": "FPS",
        "sampling_rules_add": "Add Row",
        "sampling_rules_remove": "Remove Selected",
        "sampling_rules_apply": "Apply Rules",
        "sampling_rules_empty": "Leave empty to use the base FPS for all videos.",
        "sampling_rules_invalid_row": "Rule row {row} is invalid. Check the duration and FPS format.",
        "setting_dynamic_fps_reference_duration": "Reference Duration",
        "setting_dynamic_fps_reference_duration_hint": "When video duration matches this value, dynamic mode uses the unified FPS above. Shorter videos sample more densely and longer videos sample more sparsely.",
        "setting_dynamic_fps_min": "Dynamic Min FPS",
        "setting_dynamic_fps_min_hint": "Lower bound for dynamic sampling.",
        "setting_dynamic_fps_max": "Dynamic Max FPS",
        "setting_dynamic_fps_max_hint": "Upper bound for dynamic sampling.",
        "setting_remote_max_frames": "Remote Frame Cap (Advanced)",
        "setting_remote_max_frames_hint": "Safety cap only. Usually keep default unless you process very long videos.",
        "setting_top_k_hint": "Maximum number of results returned per query.",
        "setting_search_mode_hint": "Frame mode is finer; Chunk mode is more semantic.",
        "settings_hint": "Click Save Settings to apply changes.",
        "saved_settings": "Settings saved.",
        "settings_saved_no_rebuild": "Settings saved. New values will apply to future searches.",
        "settings_saved_chunk_rebuild": "Settings saved. Chunk-related changes require index rebuild.",
        "settings_saved_full_rebuild": "Settings saved. FPS changed, full index rebuild required.",
        "settings_saved_mixed_rebuild": "Settings saved. FPS and Chunk settings changed, full rebuild required.",
        "library_vectors_title": "Local Vector File Details",
        "details_title_default": "Details",
        "details_copy_json": "Copy JSON",
        "details_export_json": "Export JSON",
        "details_empty": "No source available.",
        "ready": "Ready",
        "searching": "Searching...",
        "search_done": "Search completed in {duration:.2f}s, {count} results.",
        "no_results": "No matches found.",
        "search_failed": "Search failed.",
        "empty_query": "Enter text or upload an image first.",
        "query_too_short": "The query is too short. Describe at least the subject or action.",
        "query_generic_title": "Search Tip",
        "query_generic_hint": "This description is broad. Add subject, action, scene, or shot details.",
        "query_refined": "Normalized query: {query}",
        "warning_title": "Notice",
        "error_title": "Operation Failed",
        "success_title": "Done",
        "generic_detail": "Details: {detail}",
    },
}


def apply_copy_overrides(base_texts, language):
    merged = dict(base_texts or {})
    merged.update(COPY_OVERRIDES.get(language, {}))
    return merged
