import json
import os
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

URL = "https://v.douyin.com/osId0ScbU80/"


def fetch_ttwid() -> str:
    body = json.dumps(
        {
            "aid": 6383,
            "needFid": False,
            "region": "cn",
            "service": "www.douyin.com",
            "union": True,
        }
    ).encode()
    req = urllib.request.Request(
        "https://ttwid.bytedance.com/ttwid/union/register/",
        data=body,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        for item in resp.headers.get_all("Set-Cookie") or []:
            if item.startswith("ttwid="):
                return item.split(";", 1)[0].split("=", 1)[1]
    return ""


def write_cookie_file(path: str, ttwid: str, extra_path: str | None = None) -> None:
    lines = ["# Netscape HTTP Cookie File", "# Generated by VideoSeek test"]
    if extra_path and os.path.isfile(extra_path):
        with open(extra_path, encoding="utf-8", errors="ignore") as handle:
            for line in handle:
                if line.startswith("#") or not line.strip():
                    continue
                lines.append(line.rstrip("\n"))
    if ttwid:
        lines.append(f".douyin.com\tTRUE\t/\tTRUE\t2147483647\tttwid\t{ttwid}")
        lines.append(f"www.douyin.com\tFALSE\t/\tTRUE\t2147483647\tttwid\t{ttwid}")
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")


ttwid = fetch_ttwid()
print("ttwid fetched", bool(ttwid))
with tempfile.TemporaryDirectory() as tmp:
    cookie_path = os.path.join(tmp, "cookies.txt")
    user_cookie = os.environ.get("DOUYIN_COOKIE_FILE", "").strip()
    write_cookie_file(cookie_path, ttwid, user_cookie or None)
    cmd = ["yt-dlp", "--simulate", "--no-warnings", "--cookies", cookie_path, URL]
    result = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8", errors="ignore")
    print("exit", result.returncode)
    print(result.stdout)
    print(result.stderr)
